 	
SELECT DISTINCT A.EMPLID, A.DFLT_EE_PROF_FLG, A.BUSINESS_UNIT_GL, A.PYMNT_METHOD, B.OPRDEFNDESC, B.ACCTLOCK
  FROM PS_EX_EE_ORG_DTL A, PS_SP_BU_GL_CLSVW A1, PSOPRDEFN B
  WHERE ( A1.OPRCLASS = 'BOR_SHARE'
    AND ( A.EMPLID = B.EMPLID
     AND A.PYMNT_METHOD = 'CHK'
     AND B.ACCTLOCK = 0
     AND A.DFLT_EE_PROF_FLG = 'Y'
     AND A.BUSINESS_UNIT_GL = :3 )) 